### ISSUE TITLE
Database, schema and JDBC catalog/schema

### ISSUE THREAD

**Issue by rogerbj** [ClickHouse/clickhouse-java#1273]
Browsing the product documentation for ClickHouse it mentions the **Database** concept and term a lot. Doing the search for **Schema** it basically gives nothing. I.e. schema is as far as I can see not a concept in ClickHouse.

However, when using the JDBC driver it gives nothing back when calling `DatabaseMetaData.getCatalogs()` while `DatabaseMetaData.getSchemas()` gives a list of databases.  The same goes for `Connection.setCatalog()` which does nothing while `DatabaseMetaData.setSchema()` changes the current database. 

Why this mix-up in the ClickHouse JDBC driver? **Catalog** in the majority of drivers I have experience with is the JDBC term for Database while Schema is, well the schema.

**Comment by zhicwu** [comment]
Hi @rogerbj, as far as I know, ClickHouse does not support schema at this point. The mix-up in JDBC driver can be traced back to the very beginning - the initial version chosen schema over catalog, perhaps because MySQL JDBC driver did so. In addition, when refactoring the driver in v0.3.2, I kept it as is for consistency with mysql connector(try connect to ClickHouse using MySQL JDBC driver).

Back to your concern, I think we can introduce a new option(e.g. [databaseTerm](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-connection.html#cj-conn-prop_databaseTerm)) to use catalog instead of schema in JDBC driver. Besides, I hope to extend dbeaver/dbeaver#14773 by promoting all external datasources to catalogs(like in trino).

cc @mshustov and @alexey-milovidov in case they want to comment.

**Comment by zhicwu** [comment]
Filed dbeaver/dbeaver#19383 for DBeaver support.
