### ISSUE TITLE
Reduce overhead at server side caused by column retrieving from client side

### ISSUE THREAD

**Issue by FrankChen021** [ClickHouse/clickhouse-java#1298]
### Describe the bug
Current JDBC sends a SELECT query to ClickHouse to retrieve the columns of target table before it executes an INSERT statement.
This SELECT is special designed that it has always false filter. For example

```sql
SELECT
  timestamp,
  message
FROM
   store_all
WHERE
  0
```

If the target table is a distributed table, when ClickHouse receives such SELECT query, it will re-write this statement to query local table and dispatch the re-written SQL to all nodes in the cluster as

```sql
SELECT
  timestamp,
  message
FROM
   store
WHERE
  0
```

However, what we want is the columns of the target table, making the server dispatch this query to all nodes in the cluster is unnecessary.

This problem can be optimized  at the server side. For the server side, obviously, the filter 'WHERE 0' is always FALSE, and no need to dispatch SQL to all nodes in the cluster. But such special predicate judgement before dispatching and re-written might take more time to complete.

Client side can also do such optimization by using DESCRIBE STATEMENT.
Here we're going to get the columns of the target table, in such case, it's the distributed table. DESCRIBE the distributed table is more semantic accurate than executing a SELECT on local table.

So, my suggestion is changing the SELECT statement to DESCRIBE TABLE statement at the client side to reduce extra overhead at the server side.

**Comment by zhicwu** [comment]
Thanks @FrankChen021 for the suggestion. It was considered in the beginning but unfortunately `DESC` does not support modifiers like `EXCEPT`, not to mention it's tedious to enhance the broken SQL parser to extract all insert columns and cross check with the full list. It would be really nice if ClickHouse supports prepared statement or it can handle the false criteria in a better way,  and it's just not about Java client.

As to the specific case, I'd suggest to use input function instead, so that the type inferring no longer involves the additional query.
