### ISSUE TITLE
Recommended config settings for large selects

### ISSUE THREAD

**Issue by HunterSherms** [ClickHouse/clickhouse-java#224]
I'm running a large select over a single table and have noticed that at around 300k rows, the driver just returns an empty resultset with no error thrown, while anything smaller returns the expected results.

Are the recommendations or examples anywhere for configuration for large selects?

**Comment by thinkinerp** [comment]
you can try the param "max_result_rows"

**Comment by waitingF** [comment]
I encountered the same question, how did you solved the problem? @HunterSherms

**Comment by zhicwu** [comment]
The driver processes data row by row, rather than holding everything in memory. However, it might encounter difficulties when handling XML or JSON data formats. Since there hasn't been any recent discussion on this topic, this ticket will be closed. If you encounter any issues, please don't hesitate to create a new ticket detailing the steps to reproduce the problem using the latest version of the driver.
