### ISSUE TITLE
useServerTimeZone == true doesn't work

### ISSUE THREAD

**Issue by Dustangelms** [ClickHouse/clickhouse-java#955]
https://github.com/ClickHouse/clickhouse-jdbc/blob/c98c084e35ee68249274fcd273644545d90e82a3/clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java#L279-L282

The `GregorianCalendar` object is created using local default time zone, not server time zone.

**Comment by zhicwu** [comment]
Thanks @Dustangelms for pointing this out. It does not look correct but Calendar was used in a way to get consistent result from mysql interface. If you need to deal with timezone, it is recommended to use LocalDate/LocalDateTime/OffsetDateTime instead of legacy Date/Calendar API, also please be aware that the latter is 10 times slower.

**Comment by TheHett** [comment]
> , it is recommended to use LocalDate/LocalDateTime/OffsetDateTime instead of legacy Date/Calendar API, also please be aware that the latter is 10 times slower

We can't because ClickHouse driver uses the type `Date` and `GregorianCalendar` internal

**Comment by chernser** [comment]
Now timezone is taken from server response what should solve the issue.
